---
abstract: 'A Not-quite-so-low-level HTTP connection (client)'
author:
  - 'Ashley Willis <ashley+perl@laurelmail.net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-HTTP-Client
version: 0.001
